updates

diff --git a/.local/bin/git b/.local/bin/git
--- a/.local/bin/git
+++ b/.local/bin/git
@@ -11,4 +11,8 @@ DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
 
 gpg-connect-agent updatestartuptty /bye &> /dev/null
 mapfile -t COMMAND < <(get-wrapped-binary-command "${DIR}/git")
+if ((${#COMMAND[@]} == 0)); then
+  echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+  exit 1
+fi
 exec -- "${COMMAND[@]}" "$@"
diff --git a/.local/bin/highlight b/.local/bin/highlight
--- a/.local/bin/highlight
+++ b/.local/bin/highlight
@@ -13,6 +13,10 @@ readonly DEFAULT_STYLE='solarized-dark'
 readonly DEFAULT_TABWIDTH=4
 
 mapfile -t COMMAND < <(get-wrapped-binary-command "${WRAPPER_PATH}")
+if ((${#COMMAND[@]} == 0)); then
+  echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+  exit 1
+fi
 exec -- "${COMMAND[@]}" \
   --data-dir="${DEFAULT_DATA_DIR}" \
   --style="${DEFAULT_STYLE}" \
diff --git a/.local/bin/nvim b/.local/bin/nvim
--- a/.local/bin/nvim
+++ b/.local/bin/nvim
@@ -17,6 +17,10 @@ main() {
     exec -- "${LOCAL_NVIM_BIN}" "$@"
   fi
   mapfile -t cmd < <(get-wrapped-binary-command "${WRAPPER_PATH}")
+  if ((${#cmd[@]} == 0)); then
+    echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+    exit 1
+  fi
   exec -- "${cmd[@]}" "$@"
 }
 
diff --git a/.local/bin/rofi b/.local/bin/rofi
--- a/.local/bin/rofi
+++ b/.local/bin/rofi
@@ -9,6 +9,10 @@ WRAPPER_PATH="$(readlink -f "$0")"
 main() {
   local cmd
   mapfile -t cmd < <(get-wrapped-binary-command "${WRAPPER_PATH}")
+  if ((${#cmd[@]} == 0)); then
+    echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+    exit 1
+  fi
   exec -- "${cmd[@]}" -i "$@"
 }
 
diff --git a/.local/bin/rsync b/.local/bin/rsync
--- a/.local/bin/rsync
+++ b/.local/bin/rsync
@@ -7,4 +7,8 @@ WRAPPER_PATH="$(readlink -f "$0")"
 
 gpg-connect-agent updatestartuptty /bye &> /dev/null
 mapfile -t COMMAND < <(get-wrapped-binary-command "${WRAPPER_PATH}")
+if ((${#COMMAND[@]} == 0)); then
+  echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+  exit 1
+fi
 exec -- "${COMMAND[@]}" "$@"
diff --git a/.local/bin/ssh b/.local/bin/ssh
--- a/.local/bin/ssh
+++ b/.local/bin/ssh
@@ -19,4 +19,8 @@ echo "XAUTHORITY=${XDG_RUNTIME_DIR}/Xauthority" >| "${HOME}/.ssh/environment"
 gpg-connect-agent updatestartuptty /bye &> /dev/null
 
 mapfile -t COMMAND < <(get-wrapped-binary-command "${WRAPPER_PATH}")
+if ((${#COMMAND[@]} == 0)); then
+  echo 1>&2 "Missing command: $(basename "${WRAPPER_PATH}")"
+  exit 1
+fi
 exec -- "${COMMAND[@]}" "$@"
