fix(git-sensible-update): detect updates changing the current branch

diff --git a/.my_scripts/sysadmin/git-sensible-update b/.my_scripts/sysadmin/git-sensible-update
--- a/.my_scripts/sysadmin/git-sensible-update
+++ b/.my_scripts/sysadmin/git-sensible-update
@@ -2,11 +2,17 @@
 #
 # Syncs a git repo with upstream and checks out the latest "sensible" version
 # with the following order of precedence:
-# - The newest tag newer than HEAD if it exists
+# - The newest tag newer than HEAD (if it exists)
 # - Default branch (usually master) if it's newer than HEAD
 #
 # Assumptions:
 # 1. Every git repo has a remote named origin
+#
+# TODO: Support an explicit update strategy.
+# This will enable to control when to prefer tags over the default branch
+# (always? when they are too old?). Currently, a repo can get stuck in a tagged
+# commit because it happened to be the tip of the default branch.
+# It can be provided in .gitmodules for submodules or the git config.
 
 # See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
 set -o errexit -o errtrace -o nounset -o pipefail
@@ -221,6 +227,10 @@ checkout_if_safe() {
   git checkout "${rev}"
 }
 
+# Return values:
+# - 0: checked out the revision, it has all existing commits and new ones
+# - 1: didn't check out the revision, already pointing to same one
+# - 2: didn't check out the revision, it doesn't have all existing commits
 checkout_if_newer() {
   local rev="$1"
   local rev_desc="${2:-$1}"
@@ -228,13 +238,13 @@ checkout_if_newer() {
   num_missing_commits="$(get_num_missing_commits "${rev}")"
   if ((num_missing_commits != 0)); then
     _log_info "${rev_desc} does not have all HEAD commits, leaving HEAD as is"
-    return 1
+    return 2
   fi
   # NOTE: The ^{} part is used to dereference annotated tags, see:
   # https://stackoverflow.com/q/66913267/1014208
   if [[ "$(git rev-parse HEAD)" == "$(git rev-parse "${rev}^{}")" ]]; then
     _log_info "HEAD already pointing to ${rev_desc}, leaving HEAD as is"
-    return 0
+    return 1
   fi
   _log_info_bold "${rev_desc} has more commits than HEAD, checking it out"
   checkout_if_safe "${rev}"
@@ -247,13 +257,25 @@ checkout_if_newer() {
   fi
 }
 
+rollback_head() {
+  local original_head_sha1="$1"
+  local original_head_branch="$2"
+  if [[ -n "${original_head_branch}" ]]; then
+    git checkout --quiet "${original_head_branch}"
+    git reset --hard --quiet "${original_head_sha1}"
+    return
+  fi
+  git checkout --quiet "${original_head_sha1}"
+}
+
 rollback_if_lost_commits() {
-  local original_head="$1"
+  local original_head_sha1="$1"
+  local original_head_branch="$2"
   local num_lost_commits
-  num_lost_commits="$(get_num_missing_commits 'HEAD' "${original_head}")"
+  num_lost_commits="$(get_num_missing_commits 'HEAD' "${original_head_sha1}")"
   if ((num_lost_commits > 0)); then
     print_warning "Lost ${num_lost_commits} commits after update, rolling back."
-    git checkout --quiet "${original_head}"
+    rollback_head "${original_head_sha1}" "${original_head_branch}"
   fi
 }
 
@@ -270,13 +292,6 @@ maybe_stash_changes() {
   is_repo_dirty || return 1
   _log_info_bold 'Repo has uncommitted changes, stashing them.'
   git stash push
-}
-
-get_head_branch_or_commit() {
-  # `git symbolic-ref` prints the current branch if a branch is checked out, but
-  # returns an error when there's a detached HEAD. `git rev-parse` returns the
-  # SHA-1.
-  git symbolic-ref --short -q HEAD || git rev-parse HEAD
 }
 
 sensible_update() {
@@ -296,17 +311,14 @@ sensible_update() {
   if latest_tag="$(git describe --tags --abbrev=0 "origin/${branch}" 2> /dev/null)"; then
     _log_info "$(printf 'Lastest tag reachable from origin/%s: %s, datetime: %s\n' \
       "${branch}" "${latest_tag}" "$(get_commit_datetime "${latest_tag}")")"
-    if checkout_if_newer "${latest_tag}"; then
+    # If we updated to the latest tag or we're already pointing to it, return.
+    if checkout_if_newer "${latest_tag}" || (($? == 1)); then
       return
     fi
   else
     _log_info 'Did not find a tag reachable from origin/'"${branch}"
   fi
-  checkout_if_newer "${branch}" || true
-}
-
-fail() {
-  false
+  checkout_if_newer "${branch}"
 }
 
 main() {
@@ -317,10 +329,13 @@ main() {
   fi
   _log_info_bold 'Processing repo with origin '"${origin_url}"
   # Store original HEAD.
-  local original_head
-  original_head="$(get_head_branch_or_commit)"
+  local original_head_sha1
+  original_head_sha1="$(git rev-parse HEAD)"
+  # original_head_branch will be empty if on a detached head
+  local original_head_branch
+  original_head_branch="$(git symbolic-ref --short -q HEAD)" || true
   # Rollback HEAD if anything goes wrong.
-  trap '(($? != 0 )) && git checkout --quiet "${original_head}"' \
+  trap '(($? != 0 )) && rollback_head "${original_head_sha1}" "${original_head_branch}"' \
     EXIT SIGABRT SIGHUP SIGINT SIGTERM SIGPIPE SIGQUIT
   local default_branch
   if ! default_branch="$(get_default_branch origin)"; then
@@ -335,11 +350,21 @@ main() {
   local dirty=0
   maybe_stash_changes && dirty=1
   merge_and_maybe_push "${default_branch}"
-  # Rollback HEAD since sensible_update expects the original HEAD before deciding
-  # how to update.
-  git checkout --quiet "${original_head}"
-  sensible_update "${default_branch}"
-  rollback_if_lost_commits "${original_head}"
+  # Rollback HEAD since sensible_update expects the original HEAD before
+  # deciding how to update.
+  # NOTE: this isn't a perfect rollback because it checks out a detached head,
+  # but we may have been tracking a branch. We can't just check out the branch
+  # because it may have changed after fetching the remotes and merging them. We
+  # also don't want to do a full rollback like rollback_head does, since it can
+  # remove commits from the default branch which we may want to check out in the
+  # update.
+  git checkout --quiet "${original_head_sha1}"
+  if sensible_update "${default_branch}"; then
+    rollback_if_lost_commits "${original_head_sha1}" "${original_head_branch}"
+  else
+    # See note above, we roll back the head branch to the head commit.
+    rollback_head "${original_head_sha1}" "${default_branch}"
+  fi
   if ((dirty)) && ! git stash pop; then
     print_error 'Could not apply stashed changes'
     exit 2
